http:
  port: "8081"
  host: localhost
  path: "/deploy"
  
anypoint:
  user.name: "userName"
  apiProfilePath: "https://anypoint.mulesoft.com/accounts/api/profile"
  listAppPath: "https://anypoint.mulesoft.com/hybrid/api/v2/organizations/{orgid}/environments/{envid}/deployments"
  deploymentPath: "https://anypoint.mulesoft.com/hybrid/api/v2/organizations/{orgid}/environments/{envid}/deployments"
  appDetailsPath: "https://anypoint.mulesoft.com/hybrid/api/v2/organizations/{orgid}/environments/{envid}/deployments/{appid}"
  source:
    envId: "<source.envId>"
    orgId: "<source.orgId>"