#%RAML 1.0
title: hybrid-bulk-deploy
mediaType: [application/json]

types:
  rftMigrationDetails: !include dataTypes/rtfMigrationDetails.raml
  
    
  
traits:
  commonHeaders: !include traits/commonHeaders.raml
  


/migrate/rtf:
  post:
    is: [commonHeaders]
    body:
      application/json:
        type: rftMigrationDetails
        
          
    responses:
      202:
        body:
          application/json:


            

            
            

